name: Step 0, Start

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  start:
    if: ${{ github.actor == github.repository_owner }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create starter file
        run: echo "# My Prompts" > prompts.md

      - name: Commit starter file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Create starter prompts.md"
          git push

      - name: Update to step 1
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 0
          to_step: 1