name: Step 2, Few-Shot

on:
  create:

jobs:
  check-branch:
    if: github.ref_type == 'branch' && contains(github.ref, 'few-shot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update to step 3
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3