# Celebrate Completion

# Adds a celebratory comment when prompts document is merged
name: Celebrate Completion
on:
  pull_request:
    types:
      - closed

jobs:
  celebrate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Celebrate completion
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Prompts document completed! 🎉 Congratulations on finishing your prompts!'
            })
